apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: seamless
  name: seamless
spec:
  replicas: 2 
  selector:
    matchLabels:
      run: seamless
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: seamless
    spec:
      containers:
      - image: seunglab/seamless:cuda10
        name: seamless
        imagePullPolicy: Always
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: awssecret
                key: acc_key
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: awssecret
                key: secret_key
          - name: AWS_DEFAULT_REGION
            valueFrom:
              secretKeyRef:
                name: awssecret
                key: region
        command: ["/bin/sh"]
        args: ["-c", "python inference/worker.py --model_path ../models/sergiy_trans_minnie_v1_m8m10 --src_path gs://seunglab2/minnie_v1/raw_image --src_mask_path gs://seunglab2/minnie_v1/raw_image/resin_mask --src_mask_mip 8 --src_mask_val 1 --tgt_mask_path gs://seunglab2/minnie_v1/raw_image/resin_mask --tgt_mask_mip 8 --tgt_mask_val 1 --dst_path gs://seunglab2/minnie_v1/alignment/m8m10/pairwise_tmacrina_v1 --mip 6 --max_mip 8 --render_low_mip 6 --render_high_mip 8 --bbox_start 80000 80000 19900 --bbox_stop 430000 360000 21929 --bbox_mip 0 --should_contrast --max_displacement 4096 --size 8 --disable_flip_average --old_vectors --tgt_radius 3 --dir_suffix v6_inverter_distributed_ --inverter_path ../models/inverter_v7 --queue_name deepalign0"]
        resources: 
          limits:
            nvidia.com/gpu: 1
        volumeMounts:
        - name: secrets
          mountPath: /root/.cloudvolume/secrets
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: secrets
status: {}
