batch_size: 1
checkpoint_time: 100
encodings: true
epoch: 0
epochs_per_mip: 2
feature_maps:
- 12
- 18
- 24
- 30
- 36
- 42
- 48
- 54
gamma: 0.5
gamma_step: 5
gpus: '0'
height: 8
initialized_list:
- true
- true
- true
- true
- true
- true
- true
- true
iteration: 0
lambda1: 1200000.0
levels: !!python/object/apply:builtins.slice
- null
- null
- null
log_time: 1
lr: 0.001
name: nk_vf_30_minnie_jit
num_epochs: 1000000000
num_samples: null
penalty: rig
plan: all
repeats: 1
seed: null
skip_aug: true
start_lr: 0.001
supervised: false
training_set_path: !!python/object/apply:pathlib.PosixPath
- /
- usr
- people
- nkemnitz
- src
- SEAMLeSS
- whatever_train.h5
validation_set_path: null
vis_time: 50
wd: 0