batch_size: 4
catastrophic_loss: 5.0
checkpoint_time: 100
encodings: true
epoch: 98
epochs_per_mip: 2
feature_maps:
- 12
- 18
- 24
- 30
- 36
- 42
- 48
gamma: 0.5
gamma_step: 5000
gpus: 0,1,2,3
height: 7
initialized_list:
- true
- true
- true
- true
- true
- true
- true
iteration: null
lambda1: 1400000.0
levels: null
log_time: 1
lr: 0.0005
name: nk_vf_30_minnie_jit_mip3
num_epochs: 1000000000
num_samples: null
penalty: rig
plan: all
repeats: 1
seed: null
skip_aug: true
start_lr: 0.0005
supervised: false
training_set_path: !!python/object/apply:pathlib.PosixPath
- /
- usr
- people
- nkemnitz
- SEAMLeSS
- jit_mip3_folds_train_1200.h5
validation_set_path: !!python/object/apply:pathlib.PosixPath
- /
- usr
- people
- nkemnitz
- SEAMLeSS
- jit_mip3_folds_train_10.h5
vis_time: 50
wd: 0
